### ISSUE TITLE
Erro de execução ao utilizar "-permutinit 0"

### ISSUE THREAD

**Issue by bmelo** [InstitutoDOr/BROCCOLI#1]
Quando executo o programa com o parâmetro de início igual a 0, o programa encerra com erro e não gera permutações. Para contornar o problema, executo o programa uma segunda vez ajustando o parâmetro para 1.

Exemplo com código que gerou erro:

```prompt
Searchlight POSvsPRE_4D.nii -mask mask.nii -classes labels.1D -device 0 -verbose -permutations 5000 -permutinit 0
```

**Comment by sebihoefle** [comment]
Resolvido: abf42035d3da982330e73470cac25303b1f9040

**Comment by bmelo** [comment]
Thanks @sebihoefle and @riddlexter !
