### ISSUE TITLE
Erro para salvar resultado - caminho UNC

### ISSUE THREAD

**Issue by bmelo** [InstitutoDOr/BROCCOLI#3]
Quando utilizo o endereço de diretório com IP, formato Universal Naming Convention ([UNC](https://msdn.microsoft.com/en-us/library/gg465305.aspx)), a imagem com o sufixo "_acc" não é gerada.

Mensagem de erro indica que o sufixo está caindo na posição errada, junto ao IP ao invés do nome do arquivo. Segue exemplo:

![bug](https://user-images.githubusercontent.com/752946/28616895-ca0e0084-71d4-11e7-8fa9-a64470a4532b.png)

No exemplo, o IP que era 10.X.X.X se transformou em 10_acc.X.X.X .

**Comment by bmelo** [comment]
Executando mais testes, percebi que o problema não ocorre só quando utilizamos o IP. Vi que o mesmo erro ocorreu em um caminho mapeado, cujo diretório possui "**.**" no nome.

![bug em caminho mapeado](https://user-images.githubusercontent.com/752946/28617359-6e61707a-71d6-11e7-9872-570b1509ef87.png)

Acredito que o script esteja procurando por um ponto no nome para poder adicionar o sufixo. Sugiro pesquisar pelo último ponto ou pela última ocorrência da string "**.nii**".

**Comment by riddlexter** [comment]
Corrigido!
